techBar/Models/Orders.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace techBar.Models
{
    public class Orders
    {
        [Key]
        public int OrderId { get; set; }

        public string Email { get; set; }

        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }

        public List<OrderItem> OrderItems { get; set; } 
    }
}

techBar/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using techBar.Data.Cart;
using techBar.Data.Services;
using techBar.Data.Static;
using techBar.Data.ViewModels;
using techBar.Models;

namespace techBar.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IProductsCategoryService _productsCategoryService;

        private readonly ShoppingCart _shoppingCart;

        private readonly IOrdersService _ordersService;

        public OrdersController(IProductsCategoryService productsCategoryService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productsCategoryService = productsCategoryService; 
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task <IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }


        public IActionResult ShoppingCart()
        {
            
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<RedirectToActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productsCategoryService.GetCategoryIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<RedirectToActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productsCategoryService.GetCategoryIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            

            return View("OrderCompleted");
        }

    }
}

techBar/Controllers/Product_CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.EntityFrameworkCore;
using techBar.Data;
using techBar.Data.Services;
using techBar.Data.Static;
using techBar.Models;

namespace techBar.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductsCategoryController : Controller
    {
        private readonly IProductsCategoryService _service;

        public ProductsCategoryController(IProductsCategoryService productsCategoryService)
        {
            _service = productsCategoryService;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducts = await _service.GetAllAsync(n=>n.Sellers);
            return View(allProducts);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allProducts = await _service.GetAllAsync(n => n.Sellers);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filterResult = allProducts.Where(n=>n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Index",filterResult);
            }

            return View("Index",allProducts);
        }

        //GET: ProductsCategory/Details/1
        [AllowAnonymous]
        public async Task<IActionResult>Details(int id)
        {
            var productDetails = await _service.GetCategoryIdAsync(id);
            return View(productDetails);
        }

        //GET : ProductsCategory/Create
        public async Task<IActionResult> Create()
        {
            var productDropdownData = await _service.GetNewProductsDropdownsValues();

            ViewBag.Seller = new SelectList(productDropdownData.Seller, "Id", "SellerName");
            ViewBag.Manufacturer = new SelectList(productDropdownData.Manufacturers, "Id", "FullName");
            ViewBag.Product = new SelectList(productDropdownData.Products, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewProductsCategoryVM productsCategoryVM)
        {
            if (!ModelState.IsValid)
            {
                var productDropdownData = await _service.GetNewProductsDropdownsValues();

                ViewBag.Seller = new SelectList(productDropdownData.Seller, "Id", "SellerName");
                ViewBag.Manufacturer = new SelectList(productDropdownData.Manufacturers, "Id", "FullName");
                ViewBag.Product = new SelectList(productDropdownData.Products, "Id", "FullName");

                return View(productsCategoryVM);
            }
            await _service.AddNewProductCategoryAsync(productsCategoryVM);
            return RedirectToAction(nameof(Index));
        }

        //GET : ProductsCategory/Edit/1
        //[HttpPut("{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var details = await _service.GetCategoryIdAsync(id);
            if (details == null) 
            {
                return View("NotFound");
            };

            var response = new NewProductsCategoryVM()
            {
                Id = details.Id,  
                Name = details.Name,
                Description = details.Description,
                Price = details.Price,
                StartDate= details.StartDate,
                EndDate= details.EndDate,
                ImageURL = details.ImageURL,
                ProductCategory = details.ProductCategory,
                SellerId = details.SellerId,
                ManufacturerId = details.ManufacturerId,
                ProductsIds = details.Products_Categories.Select(n => n.ProductId).ToList()
            };


            var productDropdownData = await _service.GetNewProductsDropdownsValues();

            ViewBag.Seller = new SelectList(productDropdownData.Seller, "Id", "SellerName");
            ViewBag.Manufacturer = new SelectList(productDropdownData.Manufacturers, "Id", "FullName");
            ViewBag.Product = new SelectList(productDropdownData.Products, "Id", "FullName");

            return View(response);
            
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewProductsCategoryVM productsCategoryVM)
        {
            if (id != productsCategoryVM.Id)
            {
                View("NotFound");
            }

            if (!ModelState.IsValid)
            {
                var productDropdownData = await _service.GetNewProductsDropdownsValues();

                ViewBag.Seller = new SelectList(productDropdownData.Seller, "Id", "SellerName");
                ViewBag.Manufacturer = new SelectList(productDropdownData.Manufacturers, "Id", "FullName");
                ViewBag.Product = new SelectList(productDropdownData.Products, "Id", "FullName");

                return View(productsCategoryVM);
            }
            //Error Causing here.
            await _service.UpdateProductAsync(productsCategoryVM);
            return RedirectToAction(nameof(Index));
        }
    }
}

techBar/Views/Orders/Index.cshtml
@model List<Orders>
@{
    ViewData["Title"] = "All orders";
}
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>List of all your orders</h4>
        </p>

        <table class="table">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Items</th>
                    <th>Total</th>
                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>User</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach(var orders in Model)
                {
                    <tr>
                        <td class="align-middle">
                            @orders.OrderId
                        </td>
                        <td class="align-middle">
                            <ul style="list-style-type:none">
                                @foreach(var item in orders.OrderItems)
                                {
                                    <li>
                                        <div class="alert alert-info" role="alert">
                                            <span class="badge bd-success">@item.Amount</span>[@item.Price.ToString("c")] - @item.Productscategory.Name
                                        </div>
                                    </li>
                                    
                                }
                            </ul>
                        </td>
                        <td class="align-middle">
                            @orders.OrderItems.Select(m => m.Productscategory.Price * m.Amount).Sum().ToString("c")
                        </td>
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <td class="align-middle">
                                @orders.User.FullName
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

techBar/Views/Orders/OrderCompleted.cshtml
<div class="row">
    <div class="col-md-6 offset-3 alert alert-success text-center">
        <h2>Order Completed successfully</h2>
        <p>You can check all your Orders section of your profile</p>
        <hr />
        <p>Thank you!</p>
    </div>
</div>

techBar/Views/Orders/ShoppingCart.cshtml
@using techBar.Data.ViewModels;
@model ShoppingCartVM

@{
    ViewData["Title"] = "Shopping Cart summary";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h2>Your Shopping Cart summery</h2>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Selected Amout</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="align-middle">@item.Amount</td>
                        <td class="align-middle">@item.ProductsCategory.Name</td>
                        <td class="align-middle">@item.ProductsCategory.Price.ToString("c")</td>
                        <td class="align-middle">@((item.Amount*item.ProductsCategory.Price).ToString("c"))</td>
                        <td class="align-middle">
                            <a class="text-danger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart"
                                asp-route-it="@item.ProductsCategory.Id">
                                <i class="bi bi-cart-dash"></i>
                            </a>
                            |
                            <a class="text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart"
                               asp-route-it="@item.ProductsCategory.Id">
                               <i class="bi bi-cart-plus"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total:</b></td>
                    <td>
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div class="text-end">
            <div class="btn-group">
                @*<a class="btn btn-outline-primary" asp-action="CompleteOrder">
                    Complete order
                </a>*@
                <div id="paypal-btn"></div>
                <span style="padding:5px"></span>
                <a class="btn btn-outline-success" asp-controller="ProductsCategory" asp-action="Index">
                    Add more items
                </a>
            </div>
        </div>

    </div>
</div>
@section Scripts{
    
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>

    <script>

        let _total = @Html.Raw(Model.ShoppingCartTotal);

        paypal.Button.render({
            //Configure environment
            env:'sandbox',
            client: {
                sandbox: 'AQRp3B3jwL-cVrGs4OUlNPAOKQTodvEEjfPeg_6L85BRjug9RNZSzUnu-Cjoum2E1_bdYFTRJoGFrE9J'
            },

            //Customize button
            locale:'en_US',
            style:{
                size:'small',
                color:'gold',
                shape:'pill'
            },
            commit:true,
            
            //Set up Paymet
            payment:function(data,actions){
                return actions.payment.create({
                    transactions:[{
                        amount:{
                            total: _total,
                            currency:'CAD'
                        }
                    }]
                });
            },

            //Execute the payment 
            onAuthorize: function(data,actions){
                return actions.payment.execute().then(function(){
                    var url = '@Url.Action("CompleteOrder","Orders",new { })';
                    window.location.href=url;
                });
            }

        }, '#paypal-btn');
    </script>
}