techBar/Controllers/ManufacturerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using techBar.Data;
using techBar.Data.Services;
using techBar.Data.Static;
using techBar.Models;

namespace techBar.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class ManufacturerController : Controller
    {
        private readonly IManufacturerService _service;

        public ManufacturerController(IManufacturerService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allManufacturer = await _service.GetAllAsync();
            return View(allManufacturer);
        }

        //GET: manufacturerDetails/details/1
        
        public async Task<IActionResult> Details(int id)
        {
            var manufacturerDetails = await _service.GetByIdAsync(id);
            if (manufacturerDetails == null)
            {
                return View("NotFound");
            }
            return View(manufacturerDetails);
        }

        //GET: Manufacturer/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public Task<IActionResult> Create([Bind("ProfilePitctureURL,FullName,Bio")] Manufacturer manufacturer)
        {
            if (!ModelState.IsValid)
            {
                View(manufacturer);
            }
            _service.AddAsync(manufacturer);
            return Task.FromResult<IActionResult>(RedirectToAction(nameof(Index)));
        }

        //GET: Manufacturer/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var manufacturerDetails = await _service.GetByIdAsync(id);
            if (manufacturerDetails == null)
            {
                return View("NotFound");
            }
            return View(manufacturerDetails);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePitctureURL,FullName,Bio")] Manufacturer manufacturer)
        {
            if (!ModelState.IsValid)
            {
                View(manufacturer);
            }
            if (id == manufacturer.Id)
            {
                await _service.UpdateAsync(id, manufacturer);
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturer);
        }

        //Get: Product/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var manufacturerDetails = await _service.GetByIdAsync(id);

            if (manufacturerDetails == null)
            {
                return View("NotFound");
            }
            return View(manufacturerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manufacturerDetails = await _service.GetByIdAsync(id);
            if (manufacturerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

techBar/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using techBar.Data.Cart;
using techBar.Data.Services;
using techBar.Data.Static;
using techBar.Data.ViewModels;
using techBar.Models;

namespace techBar.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IProductsCategoryService _productsCategoryService;

        private readonly ShoppingCart _shoppingCart;

        private readonly IOrdersService _ordersService;

        public OrdersController(IProductsCategoryService productsCategoryService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _productsCategoryService = productsCategoryService; 
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task <IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }


        public IActionResult ShoppingCart()
        {
            
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<RedirectToActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _productsCategoryService.GetCategoryIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<RedirectToActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _productsCategoryService.GetCategoryIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            

            return View("OrderCompleted");
        }

    }
}

techBar/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using techBar.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using techBar.Data.Services;
using techBar.Models;
using Microsoft.AspNetCore.Authorization;
using techBar.Data.Static;

namespace techBar.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductController : Controller
    {
        private readonly IProductService _service;

        public ProductController(IProductService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        
        //Get: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                View(product);
            }
            _service.AddAsync(product);
            return Task.FromResult<IActionResult>(RedirectToAction(nameof(Index)));
        }

        //Get: Product/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var productDetails = await _service.GetByIdAsync(id);

            if (productDetails == null)
            {
                return View("NotFound");
            }
            return View(productDetails);
        }

        //Get: Product/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetByIdAsync(id);

            if (productDetails == null)
            {
                return View("NotFound");
            }
            return View(productDetails);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePitctureURL,FullName,Bio")] Product product)
        {
            if (!ModelState.IsValid)
            {
                View(product);
            }
            await _service.UpdateAsync(id, product);
            return RedirectToAction(nameof(Index));
        }



        //Get: Product/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var productDetails = await _service.GetByIdAsync(id);

            if (productDetails == null)
            {
                return View("NotFound");
            }
            return View(productDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

techBar/Controllers/SellersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using techBar.Data;
using techBar.Data.Services;
using techBar.Data.Static;
using techBar.Models;

namespace techBar.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class SellersController : Controller
    {
        private readonly ISellersService _service;

        public SellersController(ISellersService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allSellers = await _service.GetAllAsync();
            return View(allSellers);
        }

        //GET: Sellers/create

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public Task<IActionResult> Create([Bind("logo,SellerName,Description")] Sellers sellers)
        {
            if (!ModelState.IsValid)
            {
                View(sellers);
            }
            _service.AddAsync(sellers);
            return Task.FromResult<IActionResult>(RedirectToAction(nameof(Index)));
        }


        //****************************************************************************************************************************

        //Get: Sellers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var sellersDetails = await _service.GetByIdAsync(id);

            if (sellersDetails == null)
            {
                return View("NotFound");
            }
            return View(sellersDetails);
        }

        //Get: Sellers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var sellersDetails = await _service.GetByIdAsync(id);

            if (sellersDetails == null)
            {
                return View("NotFound");
            }
            return View(sellersDetails);
        }

        [HttpPost()]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,logo,SellerName,Description")] Sellers sellers)
        {
            if (!ModelState.IsValid)
            {
                View(sellers);
            }
            await _service.UpdateAsync(id, sellers);
            return RedirectToAction(nameof(Index));
        }



        //Get: Product/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var sellersDetails = await _service.GetByIdAsync(id);

            if (sellersDetails == null)
            {
                return View("NotFound");
            }
            return View(sellersDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sellersDetails = await _service.GetByIdAsync(id);
            if (sellersDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

techBar/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Product" asp-action="Index">Home Page</a>
    </div>
</div>

techBar/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px; " class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

techBar/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arror-in-right"></i> Log in
    </a>
    <span style="padding:5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{
    @*User Profile Section*@

    <div class="dropdown">
        <a class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" id="profile-btn" data-toggle="dropdown"
           aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </a>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i>Orders
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i>Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding:5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i>Log out
        </button>
    </form>

}

techBar/Views/Shared/_Layout.cshtml
<!--
    Some Data Added here. 
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - techBar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/techBar.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="ProductsCategory" asp-action="Index">techBar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        

                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="background: none; color: black; border:none">
                                    <i class="bi bi-gear"></i>Management
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Sellers" asp-action="Index"><i class="bi bi-person-badge"></i>Sellers</a></li>
                                    <li><a class="dropdown-item" asp-controller="Manufacturer" asp-action="Index"><i class="bi bi-building"></i>Manufacturer</a></li>
                                    <li><a class="dropdown-item" asp-controller="Product" asp-action="Index"><i class="bi bi-basket-fill"></i>Product</a></li>
                                </ul>
                            </div>
                        }
                        
                    </ul>
                    <form class="d-none d-md-inline-block form-check-inline ms-auto me-0 me-md-3 my-md-0" style="padding-right: 25px;" asp-controller="ProductsCategory" asp-action="Filter">
                        <div class="input-group">
                            <input name="searchString" type="text" class="form-control" placeholder="Search for a movie...">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                        </div>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <partial name="_Identity.cshtml"/>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="width:auto;">
        <div class="container">
            &copy; 2023 - techBar
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>